### ISSUE TITLE
`lvl new` finishes with error on Windows

### ISSUE THREAD

**Issue by italodirenzo93** [badassery/laravel-up#11]
Attempting to run `lvl new` on Windows results in the following error output after the `Creating your app!...done" message is output. No Laravel app is created.

```
cd: no such file or directory: D:/Code/hello-laravel-up
Error: ENOENT: no such file or directory, open 'D:/Code/hello-laravel-up/.env.example'
    at Object.parseFileSync (C:/Users/Italo/AppData/Local/Yarn/Data/global/node_modules/envfile/source/index.js:86:18)
    at Object.exports.publishEnvironment (C:/Users/Italo/AppData/Local/Yarn/Data/global/node_modules/@badassery/laravel-up/lib/actions/publish-environment.js:42:44)
    at async New.run (C:/Users/Italo/AppData/Local/Yarn/Data/global/node_modules/@badassery/laravel-up/lib/commands/new.js:40:9)
    at async New._run (C:/Users/Italo/AppData/Local/Yarn/Data/global/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (C:/Users/Italo/AppData/Local/Yarn/Data/global/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (C:/Users/Italo/AppData/Local/Yarn/Data/global/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (C:/Users/Italo/AppData/Local/Yarn/Data/global/node_modules/@oclif/command/lib/command.js:44:20)
```

**Comment by WonderPanda** [comment]
@italodirenzo93 Thanks for reporting this. Can you share the output when run with the `-v` flag so we can see the full output?

I expect that it's this portion of the docker command that's run as part of creation: `--user $(id -u):$(id -g)`

**Comment by italodirenzo93** [comment]
`-v` option produced the same output but with this extra little piece of information.
```
unknown shorthand flag: 'g' in -g)
```

**Comment by WonderPanda** [comment]
Yeah culprit is definitely the snippet I posted above. I'm not sure if it's even necessary to set the `--user` arg when running on Windows.

Each command class has a config object available on `this.config` which has tons of contextual information including the platform that the CLI is running on:

https://oclif.io/docs/config

We could make it so that the docker command is conditional based on the underlying OS as a possible solution
